### ISSUE TITLE
widgets autogen v2

### ISSUE THREAD

**Issue by KaruroChori** [KaruroChori/vs-fltk#24]
There are several changes needed to the widget auto-generation or code:
- [x] New schema to support missing features, like the `semantic` flag and splitting fields into `getter`, `setter` and `parser` methods.
- [ ] Adapt the older codegen code to use the new schema
- [ ] Adapt all schema files to the new format
- [ ] Complete the getter/setter interface at for embedded C scripts
- [ ] Complete the getter/setter interface at for embedded JS scripts
- [ ] Move parser and serializer helpers in a better place
- [ ] Expose the special `value` field for widgets like `fl:input`, so that we can use them later on for stored secrets.
- [ ] Remove the previous code & check for ood documentation based on that.

**Comment by KaruroChori** [comment]
I evaluated some of the alternatives, and I deemed frozen not to be suitable because of https://github.com/lazy-eggplant/vs.templ/issues/7
Dispatchers will be most likely implemented via gperf.
