### ISSUE TITLE
Missing workflows for v0.1.1

### ISSUE THREAD

**Issue by KaruroChori** [KaruroChori/vs-fltk#48]
The actual milestone for [v0.1.1-alpha](https://github.com/KaruroChori/vs-fltk/milestone/1) is almost done & significant changes in code will not be merged for now.  
There are just minor adjustments to be added to the current CI pipeline:
- [ ] Add meson test run on current workflows
- [ ] Task to generate flatpak on release & attach it to the release
- [ ] Task to generate the full source distribution on release via meson

Any other step currently reported @ [releasing](./docs/developers/releasing.md) is manually handled for now.

**Comment by KaruroChori** [comment]
I decided that all images/distributions which are not source and dockers will be handled externally.
So:
- debian
- arch packets
- flatpak
- brew
All this will be in https://github.com/lazy-eggplant/vs.autobuilds

Docker I think would be better to stay here, as it is meant to support the development process. So, by accepting #21 and adding [meson releases](https://mesonbuild.com/Creating-releases.html) this task is done, and any delay in flatpak will be a concern of the other repo.
