### ISSUE TITLE
**`[TRACKER]`** fltk widgets tracker

### ISSUE THREAD

**Issue by KaruroChori** [KaruroChori/vs-fltk#53]
Full tracker of any `fltk` widget requiring integration (and some custom but still based on `fltk`).
For complex cases and proposal for their integration, let's have a separate issue each.  
This issue will be pinned and is constantly revised as new proposals are made.

## Flow containers
- [ ] [flex](https://fltk.gitlab.io/fltk/classFl__Flex.html)
- [ ] [grid](https://fltk.gitlab.io/fltk/classFl__Grid.html)
- [ ] [scroll](https://fltk.gitlab.io/fltk/classFl__Scroll.html)
- [ ] [pack](https://fltk.gitlab.io/fltk/classFl__Pack.html)

## Custom widgets
- [ ] markdown: display a native markdown document (possibly including other widgets as xml)
- [ ] ui-action: run actions on the ui simulating a user. Used for automation and for documentation purposes
